// Components
// Utilities
import type { Metadata } from 'next'

// Hooks
// Styles
import '../styles/globals.css'

// Interfaces

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
